# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='concluida',
            field=models.BooleanField(default=False, verbose_name='concluida'),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='M', max_length=1, verbose_name='Prioridade'),
        ),
    ]
