# Generated by Django 5.2.8 on 2025-11-27 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_concluida_alter_task_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='criado_em',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
